INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('UCAR', '000001', 'UCAR', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('NCAR', 'UCAR', 'NCAR', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('UCP', 'UCAR', 'UCP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('COMET', 'UCP', 'UCP-COMET', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('ACOM', 'NCAR', 'NCAR-ACOM', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CGD', 'NCAR', 'NCAR-CGD', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CISL', 'NCAR', 'NCAR-CISL', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('COSMIC', 'UCP', 'UCP-COSMIC', 'admin', NOW(), UUID(), 1);

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('EOL', 'NCAR', 'NCAR-EOL', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CPAESS', 'UCP', 'UCP-CPAESS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('HAO', 'NCAR', 'NCAR-HAO', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('DLS', 'UCP', 'UCP-DLS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('MMM', 'NCAR', 'NCAR-MMM', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('GLOBE', 'UCP', 'UCP-GLOBE', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('NCARDIR', 'NCAR', 'NCAR-NCARDIR', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('JOSS', 'UCP', 'UCP-JOSS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('RAL', 'NCAR', 'NCAR-RAL', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('NSDL', 'UCP', 'UCP-NSDL', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('SCIED', 'UCP', 'UCP-SciED', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CHEMMOD', 'ACOM', 'NCAR-ACOM-CHEMMOD', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('UCPDIR', 'UCP', 'UCP-UCPDIR', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('AMP', 'CGD', 'NCAR-CGD-AMP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CAS', 'CGD', 'NCAR-CGD-CAS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CCR', 'CGD', 'NCAR-CGD-CCR', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('UNIDATA', 'UCP', 'UCP-Unidata', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('VSP', 'UCP', 'UCP-VSP', 'admin', NOW(), UUID(), 1);

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CSEG', 'CGD', 'NCAR-CGD-CSEG', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('ISG', 'CGD', 'NCAR-CGD-ISG', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('OS', 'CGD', 'NCAR-CGD-OS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('TSS', 'CGD', 'NCAR-CGD-TSS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('COMMINSI', 'ACOM', 'NCAR-ACOM-COMMINSITU', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('SATREMOT', 'ACOM', 'NCAR-ACOM-SATREMOTE', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('IMAGE', 'CISL', 'NCAR-CISL-IMAGe', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('OSD', 'CISL', 'NCAR-CISL-OSD', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('TDD', 'CISL', 'NCAR-CISL-TDD', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('AOPMO', 'EOL', 'NCAR-EOL-AOPMO', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CDS', 'EOL', 'NCAR-EOL-CDS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('DFS', 'EOL', 'NCAR-EOL-DFS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('ISF', 'EOL', 'NCAR-EOL-ISF', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('RAF', 'EOL', 'NCAR-EOL-RAF', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('CSAP', 'RAL', 'NCAR-RAL-CSAP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('RSF', 'EOL', 'NCAR-EOL-RSF', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('AIM', 'HAO', 'NCAR-HAO-AIM', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('IG', 'HAO', 'NCAR-HAO-IG', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('LSV', 'HAO', 'NCAR-HAO-LSV', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('MLSO', 'HAO', 'NCAR-HAO-MLSO', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('HAP', 'RAL', 'NCAR-RAL-HAP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('STSW', 'HAO', 'NCAR-HAO-STSW', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('JNT', 'RAL', 'NCAR-RAL-JNT', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('NSAP', 'RAL', 'NCAR-RAL-NSAP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('BLT', 'MMM', 'NCAR-MMM-BLT', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('WSAP', 'RAL', 'NCAR-RAL-WSAP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('DA', 'MMM', 'NCAR-MMM-DA', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('ITS', 'MMM', 'NCAR-MMM-ITS', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('ASP', 'NCARDIR', 'NCAR-NCARDIR-ASP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('MD', 'MMM', 'NCAR-MMM-MD', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('MP', 'MMM', 'NCAR-MMM-MP', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('PM', 'MMM', 'NCAR-MMM-PM', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('RCR', 'MMM', 'NCAR-MMM-RCR', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('NCARDIRE', 'NCARDIR', 'NCAR-NCARDIR-NCARDire', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('NCARLIB', 'NCARDIR', 'NCAR-NCARDIR-NCARLIB', 'admin', NOW(), UUID(), 1); 

INSERT INTO UNIT (UNIT_NUMBER,PARENT_UNIT_NUMBER,UNIT_NAME,UPDATE_USER,UPDATE_TIMESTAMP,OBJ_ID,VER_NBR) VALUES ('AAP', 'RAL', 'NCAR-RAL-AAP', 'admin', NOW(), UUID(), 1); 
