START TRANSACTION;

SELECT * FROM NSF_CODES;

TRUNCATE TABLE NSF_CODES;

INSERT NSF_CODES (NSF_SEQUENCE_NUMBER, NSF_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
VALUES (  1,	'N/A',	'Not Applicable',	NOW(),	'admin', 1, UUID());


SELECT * FROM nsf_codes;

COMMIT;
			

            
            