START TRANSACTION;

SELECT * FROM ORGANIZATION_TYPE_LIST;
SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE ORGANIZATION_TYPE_LIST;

INSERT ORGANIZATION_TYPE_LIST (ORGANIZATION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, VER_NBR, OBJ_ID)
SELECT RIGHT(UUID_SHORT(),2) * 10, DESCRIPTION, NOW(),'admin', 1, UUID() FROM SPONSOR_TYPE;

SELECT * FROM ORGANIZATION_TYPE_LIST;

COMMIT;




