

START TRANSACTION;

SELECT * FROM krcr_parm_t 
WHERE PARM_NM = 'ALLOW_TM_WHEN_PENDING_AWARD_EXISTS';

UPDATE krcr_parm_t
SET VAL = 'N'
WHERE PARM_NM = 'ALLOW_TM_WHEN_PENDING_AWARD_EXISTS';

SELECT * FROM krcr_parm_t 
WHERE PARM_NM = 'ALLOW_TM_WHEN_PENDING_AWARD_EXISTS';

COMMIT;
